/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShortUuidRouteImport } from './routes/$shortUuid'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSubscriptionInfoRouteImport } from './routes/api/subscription-info'
import { Route as ApiPageConfigRouteImport } from './routes/api/page-config'

const ShortUuidRoute = ShortUuidRouteImport.update({
  id: '/$shortUuid',
  path: '/$shortUuid',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionInfoRoute = ApiSubscriptionInfoRouteImport.update({
  id: '/api/subscription-info',
  path: '/api/subscription-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPageConfigRoute = ApiPageConfigRouteImport.update({
  id: '/api/page-config',
  path: '/api/page-config',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$shortUuid': typeof ShortUuidRoute
  '/api/page-config': typeof ApiPageConfigRoute
  '/api/subscription-info': typeof ApiSubscriptionInfoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$shortUuid': typeof ShortUuidRoute
  '/api/page-config': typeof ApiPageConfigRoute
  '/api/subscription-info': typeof ApiSubscriptionInfoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$shortUuid': typeof ShortUuidRoute
  '/api/page-config': typeof ApiPageConfigRoute
  '/api/subscription-info': typeof ApiSubscriptionInfoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$shortUuid' | '/api/page-config' | '/api/subscription-info'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$shortUuid' | '/api/page-config' | '/api/subscription-info'
  id:
    | '__root__'
    | '/'
    | '/$shortUuid'
    | '/api/page-config'
    | '/api/subscription-info'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShortUuidRoute: typeof ShortUuidRoute
  ApiPageConfigRoute: typeof ApiPageConfigRoute
  ApiSubscriptionInfoRoute: typeof ApiSubscriptionInfoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$shortUuid': {
      id: '/$shortUuid'
      path: '/$shortUuid'
      fullPath: '/$shortUuid'
      preLoaderRoute: typeof ShortUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscription-info': {
      id: '/api/subscription-info'
      path: '/api/subscription-info'
      fullPath: '/api/subscription-info'
      preLoaderRoute: typeof ApiSubscriptionInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/page-config': {
      id: '/api/page-config'
      path: '/api/page-config'
      fullPath: '/api/page-config'
      preLoaderRoute: typeof ApiPageConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShortUuidRoute: ShortUuidRoute,
  ApiPageConfigRoute: ApiPageConfigRoute,
  ApiSubscriptionInfoRoute: ApiSubscriptionInfoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
